version: "3.8"

services:
  # ---------------------------
  # 🐇 RabbitMQ
  # ---------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Cổng message
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  # ---------------------------
  # 🔍 Elasticsearch
  # ---------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # Tắt security để test nhanh
      - ES_JAVA_OPTS=-Xms1g -Xmx1g     # Giới hạn RAM
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network

  # ---------------------------
  # 📊 Kibana (tuỳ chọn)
  # ---------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
