spring:
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/product_service?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    # Connection settings
    connection-timeout: 10000
    template:
      receive-timeout: 10000
      reply-timeout: 10000
    # Listener settings
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0

server:
  port: 8082